# Generated by Django 5.2.4 on 2025-08-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Is Processed'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='token',
            name='string',
            field=models.CharField(max_length=64, verbose_name='Token String'),
        ),
    ]
